/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Font {


  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData information = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData games = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_circular_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifying_glass = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu__1_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musical_note = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planet_earth = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_button = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hulu = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData netflix = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primevideo = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playstation = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nintendoswitch = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imdb = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData applemusic = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
